# Generated by Django 5.1 on 2024-08-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0003_category_voucher_blog_image_blog_imageheight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ship_cost',
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='handmadeshop.order'),
        ),
    ]
