# Generated by Django 5.1 on 2024-08-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0005_user_username_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='image',
        ),
    ]
