# Generated by Django 5.1 on 2024-08-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0007_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('S', 'STOCK'), ('O', 'SOLD OUT')], default='S', max_length=20),
        ),
    ]
