# Generated by Django 5.1 on 2024-09-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0008_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='content',
        ),
    ]
