# Generated by Django 5.1 on 2024-09-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0009_rename_comment_blogcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'PREPARING'), ('S', 'SHIPPING'), ('D', 'DELIVERED'), ('R', 'RETURNING'), ('C', 'CANCELED')], default='P', max_length=20),
        ),
    ]
