# Generated by Django 5.1 on 2024-09-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0011_remove_item_cart_remove_item_order_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='handmadeshop.item'),
        ),
    ]
