# Generated by Django 5.1 on 2024-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0012_alter_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='handmadeshop.item'),
        ),
    ]
