# Generated by Django 5.1 on 2024-10-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeshop', '0013_item_is_ordered_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
